sudo: required
services:
  - docker

before_install:
  - sudo apt-get update

before_script:
  - docker build -t blindspot-incluit .

script:
  - docker run --name blindspotcont -t -d blindspot-incluit
#  - docker exec blindspotcont bash -c 'cd /app/OpenVino-Blindspot-Assistance/build && build-wrapper-linux-x86-64 --out-dir bw-output make clean all'
#  - docker exec blindspotcont bash -c 'cd /app/OpenVino-Blindspot-Assistance/build &&sonar-scanner -Dsonar.projectKey=incluit_OpenVino-Blindspot-Assistance -Dsonar.organization=incluit -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectBaseDir=../src -Dproject.home=../src -Dsonar.login=58310463a5a3250d402fff5007a5df2e228d46e9'

 after_script:
  - docker images
