sudo: required
services:
  - docker

before_install:
  - sudo apt-get update
  - xhost +

before_script:
#  - docker pull openvino/ubuntu18_dev:2019_R3.1 || true
  - docker build -t blindspot-incluit .

script:
	- docker run --net=host --env="DISPLAY" -it --device /dev/dri:/dev/dri --device-cgroup-rule='c 189:* rmw' -v /dev/bus/usb:/dev/bus/usb --device=/dev/video0 --volume="$$HOME/.Xauthority:/root/.Xauthority:rw" blindspot-incluit /bin/bash
#  - docker run --name openvinocont -t -d openvinoincluit/openvino:latest
#  - docker exec openvinocont git clone https://github.com/incluit/OpenVino-Blindspot-Assistance
#  - docker exec openvinocont bash -c 'source /opt/intel/openvino/bin/setupvars.sh && cd /app/OpenVino-Blindspot-Assistance && mkdir build && cd build && source /app/OpenVino-Blindspot-Assistance/scripts/setupenv.sh && cmake .. && make'
#  - docker exec openvinocont bash -c 'cd /app/OpenVino-Blindspot-Assistance/build && build-wrapper-linux-x86-64 --out-dir bw-output make clean all'
#  - docker exec openvinocont bash -c 'cd /app/OpenVino-Blindspot-Assistance/build &&sonar-scanner -Dsonar.projectKey=incluit_OpenVino-Blindspot-Assistance -Dsonar.organization=incluit -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectBaseDir=../src -Dproject.home=../src -Dsonar.login=58310463a5a3250d402fff5007a5df2e228d46e9'

# after_script:
#  - docker images
